# Generated by Django 5.0.14 on 2026-05-08 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('wifi', 'Wi-Fi'), ('parking', 'Parking'), ('pool', 'Piscine'), ('ac', 'Climatisation'), ('breakfast', 'Petit-déjeuner'), ('restaurant', 'Restaurant'), ('gym', 'Salle de sport'), ('spa', 'Spa'), ('security', 'Sécurité'), ('laundry', 'Laverie'), ('kitchen', 'Cuisine équipée'), ('tv', 'Télévision'), ('balcony', 'Balcon'), ('generator', 'Générateur'), ('bar', 'Bar'), ('conference', 'Salle de conférence'), ('airport_shuttle', 'Navette aéroport'), ('pet_friendly', 'Animaux acceptés')], max_length=30)),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône (ex: fa-wifi)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'db_table': 'amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('establishment_type', models.CharField(choices=[('hotel', 'Hôtel'), ('residence', 'Résidence'), ('villa', 'Villa'), ('apartment', 'Appartement'), ('guesthouse', "Maison d'hôtes"), ('hostel', 'Auberge')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('quarter', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Modérée'), ('strict', 'Stricte')], default='moderate', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('rejected', 'Rejeté')], default='pending', max_length=15)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(limit_choices_to={'role': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'establishments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstablishmentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='establishments/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='establishments.establishment')),
            ],
            options={
                'db_table': 'establishment_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capacity_adults', models.PositiveSmallIntegerField(default=2)),
                ('capacity_children', models.PositiveSmallIntegerField(default=0)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('physical_room_count', models.PositiveSmallIntegerField(default=1, help_text='Nombre de chambres physiques de ce type')),
                ('size_sqm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bed_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='establishments.amenity')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='establishments.establishment')),
            ],
            options={
                'db_table': 'room_types',
                'ordering': ['establishment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('available_count', models.PositiveSmallIntegerField(default=0)),
                ('is_manually_blocked', models.BooleanField(default=False)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='establishments.roomtype')),
            ],
            options={
                'db_table': 'room_availabilities',
                'ordering': ['room_type', 'date'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='room_types/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='establishments.roomtype')),
            ],
            options={
                'db_table': 'room_type_images',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['city', 'status'], name='establishme_city_e76c97_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['establishment_type', 'status'], name='establishme_establi_5d09a2_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['avg_rating'], name='establishme_avg_rat_b94c77_idx'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['date', 'available_count'], name='room_availa_date_e129a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomavailability',
            unique_together={('room_type', 'date')},
        ),
    ]
