# Generated by Django 5.2.15 on 2026-06-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='requires_manual_validation',
            field=models.BooleanField(default=False, help_text="Si actif, l'hébergeur doit valider une réservation après le paiement."),
        ),
    ]
