# Generated by Django 5.2.15 on 2026-06-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_establishment_requires_manual_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('rejected', 'Rejeté')], default='active', max_length=15),
        ),
    ]
