# Generated by Django 5.2.15 on 2026-06-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0003_alter_establishment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='requires_manual_validation',
            field=models.BooleanField(default=True, help_text="Si actif, l'hébergeur doit valider une réservation après le paiement."),
        ),
    ]
