# Generated by Django 5.2.15 on 2026-06-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('paid', 'Payée'), ('pending_host_validation', "En attente de validation par l'hébergeur"), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('cancelled_refunded', 'Annulée et remboursée'), ('refunded', 'Remboursée'), ('rejected_by_host', "Refusée par l'hébergeur"), ('dispute', 'Litige'), ('no_show', 'Non présenté')], default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('paid', 'Payée'), ('pending_host_validation', "En attente de validation par l'hébergeur"), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('cancelled_refunded', 'Annulée et remboursée'), ('refunded', 'Remboursée'), ('rejected_by_host', "Refusée par l'hébergeur"), ('dispute', 'Litige'), ('no_show', 'Non présenté')], max_length=30),
        ),
    ]
