# Generated by Django 5.2.15 on 2026-07-03 04:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_reservation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='late_arrival_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov', 'Moov'), ('card', 'Carte bancaire')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
    ]
