# Generated by Django 5.2.15 on 2026-07-03 04:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_loyalty_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
