# Generated by Django 5.2.15 on 2026-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingmodificationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.TextField(blank=True, help_text='Preuve de paiement (numéro de transaction, reçu, etc.)'),
        ),
    ]
