# Generated by Django 5.2.15 on 2026-06-14 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('restore', 'Restauration')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_trails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_trail_model_n_d24376_idx'), models.Index(fields=['user', 'created_at'], name='audit_trail_user_id_49e1d4_idx'), models.Index(fields=['created_at'], name='audit_trail_created_34a299_idx')],
            },
        ),
    ]
