# Generated by Django 5.2.15 on 2026-06-14 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_booking_confirmed', models.BooleanField(default=True)),
                ('email_booking_cancelled', models.BooleanField(default=True)),
                ('email_booking_reminder', models.BooleanField(default=True)),
                ('email_new_message', models.BooleanField(default=True)),
                ('email_payout_ready', models.BooleanField(default=True)),
                ('email_review_received', models.BooleanField(default=True)),
                ('email_dispute_created', models.BooleanField(default=True)),
                ('sms_booking_confirmed', models.BooleanField(default=False)),
                ('sms_booking_cancelled', models.BooleanField(default=False)),
                ('sms_booking_reminder', models.BooleanField(default=True)),
                ('sms_new_message', models.BooleanField(default=False)),
                ('push_booking_confirmed', models.BooleanField(default=True)),
                ('push_booking_cancelled', models.BooleanField(default=True)),
                ('push_booking_reminder', models.BooleanField(default=True)),
                ('push_new_message', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Réservation confirmée'), ('booking_cancelled', 'Réservation annulée'), ('booking_reminder', 'Rappel de séjour'), ('payout_ready', 'Virement prêt'), ('dispute_created', 'Litige créé'), ('dispute_resolved', 'Litige résolu')], max_length=25, unique=True)),
                ('subject_template', models.CharField(max_length=200)),
                ('email_body_template', models.TextField()),
                ('sms_template', models.CharField(blank=True, max_length=160)),
                ('push_body_template', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push notification')], default='in_app', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Réservation confirmée'), ('booking_cancelled', 'Réservation annulée'), ('booking_reminder', 'Rappel de séjour'), ('new_message', 'Nouveau message'), ('payout_ready', 'Virement prêt'), ('review_received', 'Nouvel avis reçu'), ('host_verified', 'Compte hébergeur vérifié'), ('dispute_created', 'Litige créé'), ('dispute_resolved', 'Litige résolu'), ('system', 'Système'), ('promo', 'Promotion')], max_length=25),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
