# Generated by Django 5.2.15 on 2026-07-03 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Gagnés'), ('redeemed', 'Échangés'), ('expired', 'Expirés'), ('adjusted', 'Ajustés')], max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('booking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_points_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
