# Generated by Django 5.2.15 on 2026-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_alter_commissionsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
